const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Behaviors.Persist,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Button,
		C3.Plugins.sliderbar,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Cnds.IsVisible,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.System.Exps.layoutscale,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Cnds.CompareTileAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Touch.Cnds.OnHoldGesture,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.sliderbar.Cnds.CompareInstanceVar,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetWrapping,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Acts.SetHeight,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerScaleRate,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.DrawingCanvas.Acts.AddChild,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Tilemap.Acts.EraseTileRange,
		C3.Plugins.Tilemap.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Tilemap.Exps.TileAt,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Tilemap.Cnds.CompareTileStateAt,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.ZMoveToObject,
		C3.Plugins.DrawingCanvas.Acts.SetResolutionMode,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Plugins.DrawingCanvas.Acts.SetVisible,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Tilemap.Acts.SetTile,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.DrawingCanvas.Acts.MoveToLayer,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.SetOpacity,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.Json.Acts.SetObject,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Tilemap.Cnds.CompareOpacity,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Tilemap.Exps.Count,
		C3.Plugins.Tilemap.Cnds.HasTags,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Spritefont2.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Tilemap.Acts.EraseTile,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.ForEachOrdered
	];
};
self.C3_JsPropNameTable = [
	{Warmap: 0},
	{Terrain: 0},
	{Decormap: 0},
	{Bordermap: 0},
	{Neo_Terrain: 0},
	{Neo_Warmap: 0},
	{Movemap: 0},
	{Neo_Decormap: 0},
	{Neo_Bordermap: 0},
	{Campaignmap: 0},
	{Coremap: 0},
	{Sine: 0},
	{Pin: 0},
	{Choosen_unit: 0},
	{Fade: 0},
	{Bar: 0},
	{Frame: 0},
	{Panel: 0},
	{Morale: 0},
	{Scroll: 0},
	{Origin_width: 0},
	{Origin_height: 0},
	{Animation_type: 0},
	{Bulge_koeff: 0},
	{Bulge_speed: 0},
	{Active: 0},
	{Tag: 0},
	{Reverse: 0},
	{Anim_speed: 0},
	{NextTurn: 0},
	{Strech_width: 0},
	{Strech_height: 0},
	{Strech: 0},
	{Strech_speed: 0},
	{Is_Closing: 0},
	{Phase: 0},
	{Dialogue: 0},
	{ChooseCountry: 0},
	{Button_Main: 0},
	{CurTurn: 0},
	{Choose: 0},
	{Button_Campaign: 0},
	{Decision: 0},
	{Tab: 0},
	{Window: 0},
	{Button_Pause: 0},
	{Effect: 0},
	{Close_button: 0},
	{Unit_free: 0},
	{Unit_info: 0},
	{Open_powers: 0},
	{Powers_window: 0},
	{Number: 0},
	{Ready: 0},
	{Used: 0},
	{Country_power: 0},
	{Power: 0},
	{Choosen_power: 0},
	{Accept_power: 0},
	{Area: 0},
	{Checkbox: 0},
	{Side: 0},
	{Level_Tag: 0},
	{OriginY: 0},
	{Persist: 0},
	{LevelBlock: 0},
	{tag: 0},
	{DragDrop: 0},
	{Slider: 0},
	{Preview: 0},
	{Slider_line: 0},
	{Slider_things: 0},
	{Choosen: 0},
	{Tab_button: 0},
	{Window_element: 0},
	{Unical: 0},
	{Modifier: 0},
	{is_modifier: 0},
	{Modiactions: 0},
	{Choosen_modiaction: 0},
	{Accept_action: 0},
	{Ash: 0},
	{Timer: 0},
	{Config: 0},
	{Scrolling_to_Unit: 0},
	{Scroll_speed: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{DrawingCanvas: 0},
	{Country_name: 0},
	{Mark: 0},
	{Capturable: 0},
	{Country_id: 0},
	{team: 0},
	{ToX: 0},
	{ToY: 0},
	{Baracks: 0},
	{Unit: 0},
	{HP: 0},
	{Local_name: 0},
	{Move: 0},
	{Move_min: 0},
	{Atk_type: 0},
	{Armor_type: 0},
	{Def_modifier: 0},
	{Atk_modifier: 0},
	{Armor_modifier: 0},
	{Atk_min: 0},
	{Atk_max: 0},
	{Atk_consum: 0},
	{Atk_count: 0},
	{Atk_depends_HP_modifier: 0},
	{Range: 0},
	{Ranged: 0},
	{Ranged_min: 0},
	{Ranged_max: 0},
	{Weapon: 0},
	{Weapon_scale: 0},
	{Projectile: 0},
	{Prolectile_scale: 0},
	{Transport: 0},
	{Transport_scale: 0},
	{Transport_position: 0},
	{Regen: 0},
	{Terrain_regen_mod: 0},
	{Self_supply: 0},
	{Inspiration_points: 0},
	{Light_demorale_points: 0},
	{Medium_demorale_points: 0},
	{High_demorale_points: 0},
	{Inspiration_move: 0},
	{Light_demorale_move: 0},
	{Medium_demorale_move: 0},
	{High_demorale_move: 0},
	{Forestman: 0},
	{Hillman: 0},
	{Amphibia: 0},
	{Naval: 0},
	{Preparation_before_atk: 0},
	{Moralizator: 0},
	{Encirclement: 0},
	{Move_bonus: 0},
	{Max_boardings: 0},
	{Terrain_modifier: 0},
	{OldToX: 0},
	{OldToY: 0},
	{Atk_X: 0},
	{Atk_Y: 0},
	{Attacker: 0},
	{Defender: 0},
	{is_moving: 0},
	{in_water: 0},
	{Cur_attacks: 0},
	{Cur_move: 0},
	{Cur_supply: 0},
	{Cur_terrain: 0},
	{Initialized: 0},
	{Frame_utilit: 0},
	{Next_unit_var: 0},
	{Boarding_count: 0},
	{Road_progress: 0},
	{Road_max: 0},
	{Mirror: 0},
	{Blind_range: 0},
	{Ranged_Melee: 0},
	{Agility: 0},
	{Class: 0},
	{turns_fortified: 0},
	{is_skipping: 0},
	{is_fortified: 0},
	{is_sentry: 0},
	{is_healing: 0},
	{healing_modifier: 0},
	{healing_defence_malus: 0},
	{is_attacked: 0},
	{Country: 0},
	{Mapunits: 0},
	{Button_Country: 0},
	{MoveTo: 0},
	{Score: 0},
	{Rotate: 0},
	{Target: 0},
	{MoraleAura: 0},
	{Unused: 0},
	{Siege: 0},
	{Besiege_points: 0},
	{Armor_origin: 0},
	{Suply_origin: 0},
	{Supply_modifier: 0},
	{Castle: 0},
	{Source: 0},
	{Supply: 0},
	{Distance_supply: 0},
	{Road: 0},
	{Windowed: 0},
	{Unit_stats: 0},
	{Speed: 0},
	{Aqum: 0},
	{LevelName: 0},
	{Array_abilities: 0},
	{Array_countries: 0},
	{Array_levels: 0},
	{Array_terrain: 0},
	{Array_units: 0},
	{Current: 0},
	{Turner: 0},
	{Arraymap_units: 0},
	{Arraymap_country: 0},
	{Teams: 0},
	{Arraymap_teams: 0},
	{CheckBox_Dic: 0},
	{Dictionary: 0},
	{Victory_points: 0},
	{AJAX: 0},
	{JSON_Actions: 0},
	{JSON_CombatTypes: 0},
	{JSON_Modifiers: 0},
	{JSON_Unit: 0},
	{JSON_Levels: 0},
	{Fon: 0},
	{Back: 0},
	{Name: 0},
	{Anzacoria: 0},
	{City: 0},
	{Flag: 0},
	{Hat: 0},
	{Storyteller: 0},
	{DELETE_PROGRESS: 0},
	{SliderBar: 0},
	{Panel_action: 0},
	{Action_effect: 0},
	{TimelineController: 0},
	{Auxilary: 0},
	{Provinces: 0},
	{Interface: 0},
	{Arrays: 0},
	{Patches: 0},
	{Objects: 0},
	{Checkboxes: 0},
	{Block: 0},
	{Movement_rule: 0},
	{Chance: 0},
	{Ambient: 0},
	{Volume: 0},
	{Mode: 0},
	{Duration: 0},
	{In: 0},
	{Out: 0},
	{MAX_LAYOUT_SCALE: 0},
	{TouchPanID: 0},
	{TouchZoomID: 0},
	{TouchLastX: 0},
	{TouchLastY: 0},
	{InitialScale: 0},
	{TouchStartDistance: 0},
	{TouchCurrentDistance: 0},
	{TouchCurrentMidX: 0},
	{TouchCurrentMidY: 0},
	{Scroll_value: 0},
	{Province: 0},
	{EndPhase: 0},
	{Volume_factor: 0},
	{StartY: 0},
	{Text: 0},
	{Length: 0},
	{PLOT_SIZE: 0},
	{Scripted_block: 0},
	{Debug: 0},
	{Powers_count: 0},
	{Flank_power: 0},
	{Zone_of_control_factor: 0},
	{Capture_radius: 0},
	{Supply_1rad: 0},
	{Supply_2rad: 0},
	{Team: 0},
	{Level_progress: 0},
	{Max_turns: 0},
	{Turn: 0},
	{Prev_choosen_unit: 0},
	{Unit_changed: 0},
	{Instant: 0},
	{State: 0},
	{i: 0},
	{Tab_UID: 0},
	{Attacker_weapon: 0},
	{Attacker_type: 0},
	{Defender_type: 0},
	{Time_before_hit: 0},
	{Unit_ID: 0},
	{Return_value: 0},
	{Unit_UID: 0},
	{Searching: 0},
	{Action: 0},
	{Effect_name: 0},
	{Evaluation: 0},
	{Attack_processing: 0},
	{Move_cost: 0},
	{Temp_var: 0},
	{TouchX: 0},
	{TouchY: 0},
	{OldX: 0},
	{OldY: 0},
	{X: 0},
	{Y: 0},
	{Counterattack: 0},
	{RANGE_ATTACK_TIME: 0},
	{Atc_X: 0},
	{Atc_Y: 0},
	{Country_index: 0},
	{Country_turn: 0},
	{Country_team: 0},
	{Cur_turn: 0},
	{Countries: 0},
	{Damage_need: 0},
	{Turn_disembarkation: 0},
	{Fortress_captured: 0},
	{Reorganization: 0},
	{Reorganization_turn: 0},
	{Militia_arrived: 0},
	{Capital_captured: 0},
	{Turns_captured: 0},
	{Counterattack_turns: 0},
	{Need_to_heal_Injured: 0},
	{Shock_turns: 0},
	{Knights_count: 0},
	{Initiative: 0},
	{North_west_captured: 0},
	{South_west_captured: 0},
	{Capitan_lost: 0},
	{Evacuation_target: 0},
	{UPDATE_RANGE: 0},
	{TileX: 0},
	{TileY: 0},
	{Team_ID: 0},
	{Country_ID: 0},
	{FullUpdate: 0},
	{DotX: 0},
	{DotY: 0},
	{Flag_major_capture: 0},
	{Auxilary_UID: 0},
	{Road_country: 0},
	{Road_UID: 0},
	{From: 0},
	{FROM_team: 0},
	{flanking_power: 0},
	{Tile_ToX: 0},
	{Tile_ToY: 0},
	{Change_X: 0},
	{Change_Y: 0},
	{Rule: 0},
	{break: 0},
	{TEST: 0},
	{Relative_X: 0},
	{Relative_Y: 0}
];

self.InstanceType = {
	Warmap: class extends self.ITilemapInstance {},
	Terrain: class extends self.ITilemapInstance {},
	Decormap: class extends self.ITilemapInstance {},
	Bordermap: class extends self.ITilemapInstance {},
	Neo_Terrain: class extends self.ITilemapInstance {},
	Neo_Warmap: class extends self.ITilemapInstance {},
	Movemap: class extends self.ITilemapInstance {},
	Neo_Decormap: class extends self.ITilemapInstance {},
	Neo_Bordermap: class extends self.ITilemapInstance {},
	Campaignmap: class extends self.ITilemapInstance {},
	Coremap: class extends self.ITilemapInstance {},
	Choosen_unit: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	Frame: class extends self.IWorldInstance {},
	Panel: class extends self.IWorldInstance {},
	Morale: class extends self.ISpriteInstance {},
	Scroll: class extends self.ISpriteInstance {},
	NextTurn: class extends self.ISpriteInstance {},
	Dialogue: class extends self.IWorldInstance {},
	ChooseCountry: class extends self.ISpriteInstance {},
	Button_Main: class extends self.ISpriteInstance {},
	CurTurn: class extends self.ISpriteInstance {},
	Button_Campaign: class extends self.ISpriteInstance {},
	Decision: class extends self.ISpriteInstance {},
	Window: class extends self.IWorldInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Effect: class extends self.ISpriteInstance {},
	Close_button: class extends self.ISpriteInstance {},
	Unit_free: class extends self.ISpriteInstance {},
	Unit_info: class extends self.ISpriteInstance {},
	Open_powers: class extends self.ISpriteInstance {},
	Powers_window: class extends self.IWorldInstance {},
	Power: class extends self.ISpriteInstance {},
	Choosen_power: class extends self.ISpriteInstance {},
	Accept_power: class extends self.ISpriteInstance {},
	Checkbox: class extends self.ISpriteInstance {},
	Side: class extends self.ISpriteInstance {},
	LevelBlock: class extends self.ISpriteInstance {},
	Slider: class extends self.ISpriteInstance {},
	Preview: class extends self.ISpriteInstance {},
	Slider_line: class extends self.ISpriteInstance {},
	Slider_things: class extends self.ISpriteInstance {},
	Tab_button: class extends self.ISpriteInstance {},
	Window_element: class extends self.ITiledBackgroundInstance {},
	Modiactions: class extends self.ISpriteInstance {},
	Choosen_modiaction: class extends self.ISpriteInstance {},
	Accept_action: class extends self.ISpriteInstance {},
	Ash: class extends self.IParticlesInstance {},
	Config: class extends self.ITiledBackgroundInstance {},
	Cam: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Baracks: class extends self.ISpriteInstance {},
	Unit: class extends self.ISpriteInstance {},
	Weapon: class extends self.ISpriteInstance {},
	Mapunits: class extends self.ISpriteInstance {},
	Button_Country: class extends self.ISpriteInstance {},
	Projectile: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	MoraleAura: class extends self.ISpriteInstance {},
	Unused: class extends self.ISpriteInstance {},
	Transport: class extends self.ISpriteInstance {},
	Castle: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	Unit_stats: class extends self.ISpriteFontInstance {},
	Aqum: class extends self.ISpriteFontInstance {},
	LevelName: class extends self.ISpriteFontInstance {},
	Array_abilities: class extends self.IArrayInstance {},
	Array_countries: class extends self.IArrayInstance {},
	Array_levels: class extends self.IArrayInstance {},
	Array_terrain: class extends self.IArrayInstance {},
	Array_units: class extends self.IArrayInstance {},
	Turner: class extends self.IArrayInstance {},
	Arraymap_units: class extends self.IArrayInstance {},
	Arraymap_country: class extends self.IArrayInstance {},
	Teams: class extends self.IArrayInstance {},
	Arraymap_teams: class extends self.IArrayInstance {},
	CheckBox_Dic: class extends self.IDictionaryInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Victory_points: class extends self.IDictionaryInstance {},
	AJAX: class extends self.IInstance {},
	JSON_Actions: class extends self.IJSONInstance {},
	JSON_CombatTypes: class extends self.IJSONInstance {},
	JSON_Modifiers: class extends self.IJSONInstance {},
	JSON_Unit: class extends self.IJSONInstance {},
	JSON_Levels: class extends self.IJSONInstance {},
	Fon: class extends self.ISpriteInstance {},
	Back: class extends self.ITiledBackgroundInstance {},
	Anzacoria: class extends self.ISpriteInstance {},
	City: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	Hat: class extends self.ISpriteInstance {},
	Storyteller: class extends self.ISpriteInstance {},
	DELETE_PROGRESS: class extends self.IButtonInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Panel_action: class extends self.ISpriteInstance {},
	Action_effect: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Auxilary: class extends self.ISpriteInstance {},
	Provinces: class extends self.ISpriteInstance {},
	Interface: class extends self.ISpriteInstance {},
	Arrays: class extends self.IArrayInstance {},
	Patches: class extends self.IWorldInstance {},
	Objects: class extends self.ISpriteInstance {},
	Checkboxes: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {}
}